Testing if making a pull directly to dev works any better
ole-vi/BeLL-Apps pull request #91
Opened 2017-03-24 18:14 UTC by waryhermit

2017-03-31 23:10 UTC, dogi approved these changes

2017-04-10 17:33 UTC, dogi requested changes
there are 3 files which only change in whitespaces (one of them also doubles the comment line) and not to the better ;)
- [ ] `.travis.yml`
- [ ] `tests/bell.py`
- [ ] `tests/codeceptjs-init.js`

2017-04-14 00:34 UTC, waryhermit commented
@dogi I have addressed the issues you brought up and reduced the file changed count from 10 to 6. All the tests have passed for the last three commits. I think this is ready to be merged, but I want you to check it one last time first.

2017-04-14 01:39 UTC, dogi approved these changes
great ;)

2017-04-14 01:40 UTC, merged